
name: Build application

on:
  push:
    branches:
    - main

jobs:
  build-ubuntu:
    name: Build app on Ubuntu
    uses: govindarajanv/reusable-workflows/.github/workflows/dotnetbuild.yml@main


