
name: Build application

on:
  push:
    branches:
    - main

jobs:
  build-ubuntu:
    name: Build app on Ubuntu
    uses: govindarajanv/reusable-workflows/.github/workflows/dotnetbuild.yml@feature
    with:
      runs-on: ubuntu-latest
      run-tests: false
      project-folder: src
      release-branch: main  
      artifact-name: drop-ubuntu
      is_dockerized: true
      require-helm: true
      require_qa_deploy: true
      run_test_on_qa_deploy: true

